### PR TITLE
"Bug 1912531: revendor mao"

### PR DESCRIPTION
**Pull request by elmiko**

### CODE REVIEW

**Review by michaelgugino — APPROVED** [review]
/lgtm

**Comment by hardys** [comment]
Thanks!  lgtm - can anyone confirm that the needed changes for release-4.7 were picked up via https://github.com/openshift/cluster-api-provider-baremetal/pull/132 ?

**Comment by elmiko** [comment]
@hardys i looked at the linked patch, but i'm not sure

**Comment by hardys** [comment]
> @hardys i looked at the linked patch, but i'm not sure

Looking at the date https://github.com/openshift/machine-api-operator/pull/771 merged and the version at https://github.com/openshift/cluster-api-provider-baremetal/blob/release-4.7/go.mod#L8 I think we must have the fix in the release-4.7 branch already.

/approve

**Comment by derekwaynecarr** [comment]
(Patch-Manager) approved.

**Pull request merged**
