### PR TITLE
update bmo 20190708

### PR DESCRIPTION
**Pull request by dhellmann**
Update to the version of the baremetal-operator that completes the work to rename machineRef to consumerRef.

### CODE REVIEW

**Comment by hardys** [comment]
I think some recent fixes from @zaneb landed so should we update this to include those?

@dhellmann @russellb I'd like to rebase kni-installer again this week to pick up https://github.com/openshift/installer/pull/1941 so it'd be good to ensure all the openshift forks are updated before we do that.

**Comment by dhellmann** [comment]
> I think some recent fixes from @zaneb landed so should we update this to include those?
> 
> @dhellmann @russellb I'd like to rebase kni-installer again this week to pick up [openshift/installer#1941](https://github.com/openshift/installer/pull/1941) so it'd be good to ensure all the openshift forks are updated before we do that.

As a general process thing, I've been creating these date-based PRs so we can just take them incrementally. So I could close this one and open a new one with the full content, or we could take this one and I could open another with the new delta. Let me know which you prefer.

**Comment by russellb** [comment]
i'm fine landing this, and then a follow-up PR.  This shouldn't cause a problem AFAIK ...

/lgtm

**Pull request merged**
