### PR TITLE
Bug 1864352: Update leader election for release 4.5

### PR DESCRIPTION
**Pull request by elmiko**
This change backports a few updates to the leader election mechanism.

723caff153246bc0df46fd3af9bbab82dc6b8547
097869a46f4b2ac31a08b600d90a420889232345

### CODE REVIEW

**Comment by elmiko** [comment]
/retitle Bug 1864352: Update leader election for release 4.5

**Comment by Danil-Grigorev** [comment]
@dhellmann @hardys PTAL
\lgtm
\approve

**Pull request merged**
