### PR TITLE
Fix failing unit tests in actuator remediation test

### PR DESCRIPTION
**Pull request by n1r1**
@dhellmann [reported](https://github.com/openshift/cluster-api-provider-baremetal/pull/77#issuecomment-653025242) that unit tests fails locally.

This PR fixes the failing test.

### CODE REVIEW

**Comment by hardys** [comment]
Thanks - this fixes the local failures I was also seeing:

```
$ go test .
ok  	github.com/openshift/cluster-api-provider-baremetal/pkg/cloud/baremetal/actuators/machine	0.046s
```

`make unit` still has some errors elsewhere but that looks related to my environment.

Do we know how/why this worked in CI but failed locally?

/lgtm

**Comment by n1r1** [comment]
> `make unit` still has some errors elsewhere but that looks related to my environment.

I also have some errors and thought it's only on my end. This is the error I'm getting:
```
?       github.com/openshift/cluster-api-provider-baremetal/pkg/apis/baremetal  [no test files]
2020/07/06 14:30:21 failed to start the controlplane. retried 5 times: timeout waiting for process kube-apiserver to start
```


Anyway, it happens even without this PR changes.

> Do we know how/why this worked in CI but failed locally?

That's a good question. 
It was discussed in https://github.com/openshift/cluster-api-provider-baremetal/pull/72 and I see that @kirankt [created a ticket](https://github.com/openshift/cluster-api-provider-baremetal/pull/72#issuecomment-641302205) to track this, though I have no idea where do these ticket live.

**Comment by dhellmann** [comment]
While debugging this last week I noticed that there are a lot of client calls where errors aren't being checked. Does the test client return errors in the way the real client does?

**Comment by dhellmann** [comment]
See also #80

**Comment by dhellmann** [comment]
/hold

let's stop consuming CI resources in a loop

**Comment by n1r1** [comment]
> While debugging this last week I noticed that there are a lot of client calls where errors aren't being checked. Does the test client return errors in the way the real client does?

I think it does.
I guess we can also check the errors from the fake client as well.
Would you like me to do this as part of this PR or a separate one?

**Comment by dhellmann** [comment]
> > While debugging this last week I noticed that there are a lot of client calls where errors aren't being checked. Does the test client return errors in the way the real client does?
> 
> I think it does.
> I guess we can also check the errors from the fake client as well.
> Would you like me to do this as part of this PR or a separate one?

Either way is fine.

**Pull request merged**
