### PR TITLE
remove dhellmann from owners file

### PR DESCRIPTION
**Pull request by dhellmann**
It has been a while since it was reasonable for me to be an approver
in this repo, so let's remove my name from the list.

/cc @hardys
/assign @zaneb

### CODE REVIEW

**Review by kirankt — APPROVED** [review]
/lgtm

**Comment by zaneb** [comment]
Thanks Doug!
/override ci/prow/e2e-metal-ipi-ovn-ipv6
/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Pull request merged**
