### PR TITLE
Bug 1863010: ensure delete removes the link between machine and host

### PR DESCRIPTION
**Pull request by dhellmann**
The bug fix also requires a fix that hadn't been backported yet to make
the test jobs work.

### CODE REVIEW

**Comment by dhellmann** [comment]
@zaneb @hardys could you take a look at this PR now that the 4.6 version has landed? thanks!

**Comment by zaneb** [comment]
Isn't BareMetalMachineProvider a CAPM3 thing? Why are we adding CRDs for it downstream?

**Comment by dhellmann** [comment]
> Isn't BareMetalMachineProvider a CAPM3 thing? Why are we adding CRDs for it downstream?

I thought the provider spec was the name of the type for the platform-specific bits of the old-style actuator-based types. I'm not sure why we have the CRD for it (I cherry-picked the patch). We could probably remove it, but we should do that in the master branch first and backport it, since this change has already been verified in 4.6. I think the worst effect of not doing that is that we have an unused file being generated in the repo.

> 
> The patch itself looks fine.

**Comment by jwforres** [comment]
@dhellmann I am patch mgr this week, just ping me on slack when #94 is rebased and I'll mark it

**Pull request merged**
