### PR TITLE
stop generating CRDs for provider spec and status

### PR DESCRIPTION
**Pull request by dhellmann**
We do not use separate CRDs for the provider spec or status for
Machine resources. They are being generated with settings that are no
longer supported, which breaks our ability to upgrade the dependencies
in this repo.

See https://github.com/kubernetes/enhancements/pull/1111

### CODE REVIEW

**Review by rdoxenham — APPROVED** [review]
Thanks for taking the time to do this!

**Comment by hardys** [comment]
These types definitely don't exist in the deployed cluster - I was wondering why these existed :)

/approve

**Pull request merged**
