### PR TITLE
Bug 1862875: remove machine finalizer from host when deleting machine

### PR DESCRIPTION
**Pull request by dhellmann**
This PR depends on #93 and should be rebased after it merges

/hold

### CODE REVIEW

**Comment by dhellmann** [comment]
@zaneb @hardys could you take a look at this PR now that the 4.6 version has landed? thanks!

**Comment by zaneb** [comment]
Isn't BareMetalMachineProvider a CAPM3 thing? Why are we adding CRDs for it downstream?

**Comment by zaneb** [comment]
Actually, I'll move that comment to #93. This PR is just for the last patch, which
/lgtm

**Comment by dhellmann** [comment]
@jwforres this one has been rebased

**Comment by dhellmann** [comment]
@zaneb could you take another look at this, now that it has been rebased, please?

**Pull request merged**
