### PR TITLE
Switch openshift/cluster-api branch.

### PR DESCRIPTION
**Pull request by russellb**
Switch the openshift/cluster-api branch to
openshift-4.0-cluster-api-0.0.0-alpha.4, which contains the latest
rebase of cluster-api.  Providers are not to be using the master
branch of openshift/cluster-api.

### CODE REVIEW

**Comment by mhrivnak** [comment]
It looks like the AWS provider is just using the https://github.com/openshift/cluster-api/tree/openshift-4.0-cluster-api-0.0.0-alpha.4 branch, which includes the patch. That branch is also using 1.13 kube code. You should be able to change that in Gopkg.toml, run `dep ensure -u github.com/openshift/cluster-api`, and then have the patch.

That said, I don't know what the expectations are around that branch or why it includes stuff not in `master`, but using that branch would get us to the same state as the aws and libvert providers.

**Comment by ingvagabund** [comment]
As @mhrivnak describes. The master branch of openshift/cluster-api is considered dormant. Only https://github.com/openshift/cluster-api/tree/openshift-4.0-cluster-api-0.0.0-alpha.4 branch is supposed to be imported.

**Pull request merged**
