### PR TITLE
Bug 2099584: Update BMO vendor to v0.0.0-20211102102625-469cc9bf7fee

### PR DESCRIPTION
**Pull request by derekhiggins**
Our older version was missing BareMetalHostSpec.PreprovisioningNetworkDataName
which was causing the field to be removed when the bmh
was used.

### CODE REVIEW

**Comment by dtantsur** [comment]
/approve
/label backport-risk-assessed

```
baremetal-operator (main) $ git branch --contains 469cc9bf7fee --remote
  openshift/master
  openshift/release-4.10
  openshift/release-4.11
  openshift/release-4.12
  openshift/release-4.13
```

**Comment by derekhiggins** [comment]
Looking for backport-risk-assessed labels, @zaneb @hardys would you mind taking a look please.

**Comment by zaneb** [comment]
I can do this one, but we need to update [the config](https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/cluster-api-provider-baremetal/_pluginconfig.yaml#L9-L15) to include some people who are actually still on the team, like @derekhiggins @dtantsur @honza 

/approve
/label backport-risk-assessed

**Comment by derekhiggins** [comment]
> I can do this one, but we need to update [the config](https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/cluster-api-provider-baremetal/_pluginconfig.yaml#L9-L15) to include some people who are actually still on the team, like @derekhiggins @dtantsur @honza

thanks Zane, Not sure any of us are very active in this repo but happy to be added if needed

@lshilin-r now looking for a cherry-pick-approved label if you have a chance.

**Pull request merged**
