### PR TITLE
Bug 1907614: Update kubernetes deps to 1.20

### PR DESCRIPTION
**Pull request by kirankt**
Update vendored versions of k8s.io from v0.19.x to v0.20.0 to align with K8s 1.20.

### CODE REVIEW

**Comment by kirankt** [comment]
/hold 
We need machine-api-operator to catch up to 1.20 before we can update the this repo.

**Comment by kirankt** [comment]
Depends on: https://github.com/openshift/machine-api-operator/pull/778

**Comment by stbenjam** [comment]
Looks like this needs an update to get https://github.com/openshift/machine-api-operator/pull/705

**Comment by kirankt** [comment]
/close
Replaced by #132

**Pull request closed without merging**
