### PR TITLE
Bug 1838431: Machine Remediation Backport to 4.4

### PR DESCRIPTION
**Pull request by n1r1**
Manual cherry pick of https://github.com/openshift/cluster-api-provider-baremetal/pull/59 in order to backport machine remediation feature to 4.4

### CODE REVIEW

**Comment by stbenjam** [comment]
CAPBM is missing e2e-metal-ipi. https://github.com/openshift/release/pull/9462 will enable it, I'd like to see that pass first.

/hold

**Comment by eparis** [comment]
/hold
we do not backport features to z-streams. Please provide justification why we would consider doing this. In a private comment in the BZ might be appropriate since the business justification would obviously contain customer information.

**Comment by n1r1** [comment]
@eparis, I've added justification to bugzilla. 
thanks

**Comment by bparees** [comment]
@eparis will be following up on this, but for now it's not being approved pending PM justification.

**Comment by n1r1** [comment]
Per our bugzilla discussion, I'm closing this PR

**Pull request closed without merging**
