### PR TITLE
Bug 1828003: Change cluster-api to machine-api-operator API

### LINKED ISSUE #64: change vendored cluster-api to machine-api-operator
github.com/openshift/cluster-api/ is no longer being maintained, and the code has been moved into https://github.com/openshift/machine-api-operator/

We need to update our vendoring to make that change. That also should probably mean switching finally to go modules.

### PR DESCRIPTION
**Pull request by kirankt**
Change from cluster-api to machine-api-operator API
Move to go modules
Closes #64

### CODE REVIEW

**Comment by stbenjam** [comment]
/retitle Bug 1828003: Change cluster-api to machine-api-operator API

**Comment by stbenjam** [comment]
The last CI run, dev-scripts finished so it's looking better. This looks good to me.

/lgtm
/hold

We can remove the hold once CI passes.

**Comment by hardys** [comment]
This would be easier to review if the code changes were in a separate commit to the vendor changes, but otherwise lgtm modulo CI passing

**Comment by kirankt** [comment]
> This would be easier to review if the code changes were in a separate commit to the vendor changes, but otherwise lgtm modulo CI passing

+1. I'll split the PR into two commits for clarity.

**Comment by stbenjam** [comment]
A bunch of fixes have landed, not sure if they're in the latest CI build but let's see.

/test e2e-metal-ipi

**Pull request merged**
