### PR TITLE
BUG 1877743: Bump K8s dependencies to v1.19.0

### PR DESCRIPTION
**Pull request by JoelSpeed**
Our dependencies are out of date and should be on K8s 1.19.0 before the 4.6 release to match the rest of the core components. This PR updates all of the K8s and openshift depdendencies to include the lastest 1.19.0 release.

### CODE REVIEW

**Comment by zaneb** [comment]
#110 fixes the managerWrapper error.

**Comment by zaneb** [comment]
Forcing the latest version of zapr with `go get -d github.com/go-logr/zapr@latest` seems to resolve the other build failure.

**Comment by zaneb** [comment]
There were some unit test fixes required as well. I can't push to this branch, so I pushed fixes to #96. We can retitle that one and merge it, or feel free to just push those patches here.

**Comment by JoelSpeed** [comment]
@zaneb Feel free to close this one and take over the capbm part of the attached bug in #96 👍

**Comment by zaneb** [comment]
/close
in favour of #96

**Pull request closed without merging**
